-- Add the landing page table to an existing database
--
-- Run this in hPanel -> Databases -> phpMyAdmin -> select your database -> SQL
-- tab, before using Admin -> Growth -> Landing Pages on a site that is already
-- live. Without it that screen fails with
--   The table 'main.LandingPage' does not exist
--
-- A fresh install does NOT need this: prisma/schema.sql and
-- prisma/schema-with-demo.sql already create the table.
--
-- Non-destructive: it adds a table and one nullable column. No existing row is
-- touched. Orders are never deleted with a page — Order.landingPageId is
-- ON DELETE SET NULL, so removing a funnel keeps its orders and loses only the
-- attribution.
--
-- If you re-run it, MySQL will report that the table or column already exists.
-- That is harmless; nothing below is destructive.
--
-- GENERATED by scripts/gen-landing-migration.js — do not edit by hand.

-- 1. The table itself.
CREATE TABLE `LandingPage` (
    `id` VARCHAR(191) NOT NULL,
    `title` TEXT NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `parentSlug` VARCHAR(191) NOT NULL DEFAULT 'collection',
    `status` VARCHAR(191) NOT NULL DEFAULT 'draft',
    `blocks` LONGTEXT NOT NULL,
    `metaTitle` TEXT NULL,
    `metaDesc` TEXT NULL,
    `metaKeywords` TEXT NULL,
    `ogImage` TEXT NULL,
    `canonical` TEXT NULL,
    `noIndex` BOOLEAN NOT NULL DEFAULT false,
    `gaId` TEXT NULL,
    `fbPixelId` TEXT NULL,
    `customHead` LONGTEXT NULL,
    `customBody` LONGTEXT NULL,
    `bgColor` TEXT NULL,
    `textColor` TEXT NULL,
    `fontFamily` TEXT NULL,
    `maxWidth` INTEGER NOT NULL DEFAULT 1100,
    `checkoutEnabled` BOOLEAN NOT NULL DEFAULT true,
    `checkoutHeading` TEXT NULL,
    `checkoutFields` TEXT NULL,
    `checkoutButton` TEXT NULL,
    `thankYouNote` TEXT NULL,
    `views` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `LandingPage_slug_key`(`slug`),
    INDEX `LandingPage_status_idx`(`status`),
    INDEX `LandingPage_parentSlug_slug_idx`(`parentSlug`, `slug`),
    PRIMARY KEY (`id`)
);

-- 2. Link orders to the landing page that produced them, for funnel reporting.
ALTER TABLE `Order` ADD COLUMN `landingPageId` VARCHAR(191) NULL;
ALTER TABLE `Order` ADD INDEX `Order_landingPageId_idx`(`landingPageId`);
ALTER TABLE `Order` ADD CONSTRAINT `Order_landingPageId_fkey`
  FOREIGN KEY (`landingPageId`) REFERENCES `LandingPage`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
