-- Widen columns that Prisma created as VARCHAR(191)
--
-- Prisma maps a plain `String` to VARCHAR(191) on MySQL. SQLite does not enforce
-- that limit, so over-long values saved and read back correctly in development
-- and were silently truncated on MySQL. Where the value is JSON the truncation
-- makes it unparseable and the UI renders empty — the menu, the payment logos
-- and the product images all failed this way.
--
-- MySQL truncates on write, so data already lost cannot be recovered by this
-- script; it stops the loss from continuing. Re-save the affected records after
-- running it.
--
-- Widening a column is non-destructive and keeps every row. Run it in phpMyAdmin
-- (SQL tab) against the database named in DATABASE_URL. It is safe to run more
-- than once.
--
-- Generated by scripts/gen-column-migration.js — do not edit by hand.

-- AuditLog.meta: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `AuditLog` MODIFY `meta` TEXT NULL;

-- Customer.tags: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Customer` MODIFY `tags` TEXT NULL;

-- Customer.notes: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Customer` MODIFY `notes` TEXT NULL;

-- Category.description: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Category` MODIFY `description` TEXT NULL;

-- Category.image: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Category` MODIFY `image` TEXT NULL;

-- Category.metaTitle: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Category` MODIFY `metaTitle` TEXT NULL;

-- Category.metaDesc: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Category` MODIFY `metaDesc` TEXT NULL;

-- Brand.logo: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Brand` MODIFY `logo` TEXT NULL;

-- Brand.description: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Brand` MODIFY `description` TEXT NULL;

-- Product.barcode: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `barcode` TEXT NULL;

-- Product.description: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `description` TEXT NULL;

-- Product.shortDesc: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `shortDesc` TEXT NULL;

-- Product.dimensions: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `dimensions` TEXT NULL;

-- Product.images: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Product` MODIFY `images` TEXT NOT NULL;

-- Product.tags: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `tags` TEXT NULL;

-- Product.attributes: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `attributes` TEXT NULL;

-- Product.variants: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `variants` TEXT NULL;

-- Product.careInstructions: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `careInstructions` TEXT NULL;

-- Product.metaTitle: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `metaTitle` TEXT NULL;

-- Product.metaDesc: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `metaDesc` TEXT NULL;

-- Product.metaKeywords: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `metaKeywords` TEXT NULL;

-- Product.ogImage: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `ogImage` TEXT NULL;

-- Product.canonical: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Product` MODIFY `canonical` TEXT NULL;

-- Order.paymentRef: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `paymentRef` TEXT NULL;

-- Order.shippingMethod: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `shippingMethod` TEXT NULL;

-- Order.shippingZone: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `shippingZone` TEXT NULL;

-- Order.shipArea: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `shipArea` TEXT NULL;

-- Order.shipStreet: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Order` MODIFY `shipStreet` TEXT NOT NULL;

-- Order.customerNote: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `customerNote` TEXT NULL;

-- Order.adminNote: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `adminNote` TEXT NULL;

-- Order.trackingNumber: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `trackingNumber` TEXT NULL;

-- Order.courier: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `courier` TEXT NULL;

-- Order.ipAddress: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `ipAddress` TEXT NULL;

-- Order.userAgent: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Order` MODIFY `userAgent` TEXT NULL;

-- OrderItem.productName: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `OrderItem` MODIFY `productName` TEXT NOT NULL;

-- OrderItem.sku: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `OrderItem` MODIFY `sku` TEXT NULL;

-- OrderItem.image: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `OrderItem` MODIFY `image` TEXT NULL;

-- OrderEvent.note: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `OrderEvent` MODIFY `note` TEXT NULL;

-- OrderEvent.by: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `OrderEvent` MODIFY `by` TEXT NULL;

-- Coupon.description: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Coupon` MODIFY `description` TEXT NULL;

-- Coupon.targetIds: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Coupon` MODIFY `targetIds` TEXT NULL;

-- Review.title: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Review` MODIFY `title` TEXT NULL;

-- Review.body: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Review` MODIFY `body` TEXT NOT NULL;

-- Page.title: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Page` MODIFY `title` TEXT NOT NULL;

-- Page.titleBn: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `titleBn` TEXT NULL;

-- Page.content: VARCHAR(191) NOT -> LONGTEXT NOT
ALTER TABLE `Page` MODIFY `content` LONGTEXT NOT NULL;

-- Page.excerpt: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `excerpt` TEXT NULL;

-- Page.featuredImage: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `featuredImage` TEXT NULL;

-- Page.metaTitle: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `metaTitle` TEXT NULL;

-- Page.metaDesc: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `metaDesc` TEXT NULL;

-- Page.metaKeywords: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Page` MODIFY `metaKeywords` TEXT NULL;

-- Post.title: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Post` MODIFY `title` TEXT NOT NULL;

-- Post.excerpt: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `excerpt` TEXT NULL;

-- Post.content: VARCHAR(191) NOT -> LONGTEXT NOT
ALTER TABLE `Post` MODIFY `content` LONGTEXT NOT NULL;

-- Post.coverImage: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `coverImage` TEXT NULL;

-- Post.category: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `category` TEXT NULL;

-- Post.tags: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `tags` TEXT NULL;

-- Post.authorName: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Post` MODIFY `authorName` TEXT NOT NULL DEFAULT 'BD Market Team';

-- Post.metaTitle: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `metaTitle` TEXT NULL;

-- Post.metaDesc: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Post` MODIFY `metaDesc` TEXT NULL;

-- Menu.items: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Menu` MODIFY `items` TEXT NOT NULL;

-- Banner.title: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Banner` MODIFY `title` TEXT NOT NULL;

-- Banner.subtitle: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Banner` MODIFY `subtitle` TEXT NULL;

-- Banner.image: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Banner` MODIFY `image` TEXT NOT NULL;

-- Banner.ctaLabel: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Banner` MODIFY `ctaLabel` TEXT NULL;

-- Banner.ctaHref: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Banner` MODIFY `ctaHref` TEXT NULL;

-- Banner.bgColor: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Banner` MODIFY `bgColor` TEXT NULL;

-- Banner.textColor: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Banner` MODIFY `textColor` TEXT NULL;

-- Media.filename: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Media` MODIFY `filename` TEXT NOT NULL;

-- Media.url: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Media` MODIFY `url` TEXT NOT NULL;

-- Media.mimeType: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Media` MODIFY `mimeType` TEXT NULL;

-- Media.alt: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `Media` MODIFY `alt` TEXT NULL;

-- Setting.value: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `Setting` MODIFY `value` TEXT NOT NULL;

-- ShippingZone.districts: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `ShippingZone` MODIFY `districts` TEXT NOT NULL;

-- PaymentMethod.description: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `PaymentMethod` MODIFY `description` TEXT NULL;

-- PaymentMethod.icon: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `PaymentMethod` MODIFY `icon` TEXT NULL;

-- PaymentMethod.instructions: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `PaymentMethod` MODIFY `instructions` TEXT NULL;

-- PaymentMethod.config: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `PaymentMethod` MODIFY `config` TEXT NULL;

-- PageView.path: VARCHAR(191) NOT -> TEXT NOT
ALTER TABLE `PageView` MODIFY `path` TEXT NOT NULL;

-- PageView.referrer: VARCHAR(191) NULL -> TEXT NULL
ALTER TABLE `PageView` MODIFY `referrer` TEXT NULL;
