-- Widen every column that Prisma would otherwise create as VARCHAR(191)
--
-- Prisma maps a plain `String` to VARCHAR(191) on MySQL. SQLite does not enforce
-- that limit, so over-long values saved and read back correctly in development
-- and were silently truncated on the server. Where the value is JSON the
-- truncation makes it unparseable and the interface renders empty — the menu,
-- the payment logos and the product images all failed this way.
--
-- 99 columns in total.
--
-- HOW TO RUN
--   hPanel -> Databases -> phpMyAdmin -> select your database -> SQL tab,
--   paste this whole file, press Go.
--
--   Widening a column is non-destructive and keeps every row. Do NOT re-import
--   schema.sql instead: that drops every table.
--
-- AFTERWARDS
--   MySQL truncates on write, so values already stored were lost when they were
--   saved. This stops the loss; it cannot restore what was cut. Open the menu,
--   the payment logos and any product you added, and save them again.
--   GET /api/health reports whether any critical column is still narrow.
--
-- Safe to run more than once: applying an ALTER that sets a column to the type
-- it already has is a no-op.
--
-- GENERATED by scripts/gen-column-migration.js — do not edit by hand.

ALTER TABLE `User` MODIFY `avatar` TEXT NULL;
ALTER TABLE `AuditLog` MODIFY `meta` TEXT NULL;
ALTER TABLE `Customer` MODIFY `tags` TEXT NULL;
ALTER TABLE `Customer` MODIFY `notes` TEXT NULL;
ALTER TABLE `Category` MODIFY `description` TEXT NULL;
ALTER TABLE `Category` MODIFY `image` TEXT NULL;
ALTER TABLE `Category` MODIFY `metaTitle` TEXT NULL;
ALTER TABLE `Category` MODIFY `metaDesc` TEXT NULL;
ALTER TABLE `Brand` MODIFY `logo` TEXT NULL;
ALTER TABLE `Brand` MODIFY `description` TEXT NULL;
ALTER TABLE `Product` MODIFY `barcode` TEXT NULL;
ALTER TABLE `Product` MODIFY `description` TEXT NULL;
ALTER TABLE `Product` MODIFY `shortDesc` TEXT NULL;
ALTER TABLE `Product` MODIFY `dimensions` TEXT NULL;
ALTER TABLE `Product` MODIFY `images` TEXT NOT NULL;
ALTER TABLE `Product` MODIFY `tags` TEXT NULL;
ALTER TABLE `Product` MODIFY `attributes` TEXT NULL;
ALTER TABLE `Product` MODIFY `variants` TEXT NULL;
ALTER TABLE `Product` MODIFY `careInstructions` TEXT NULL;
ALTER TABLE `Product` MODIFY `metaTitle` TEXT NULL;
ALTER TABLE `Product` MODIFY `metaDesc` TEXT NULL;
ALTER TABLE `Product` MODIFY `metaKeywords` TEXT NULL;
ALTER TABLE `Product` MODIFY `ogImage` TEXT NULL;
ALTER TABLE `Product` MODIFY `canonical` TEXT NULL;
ALTER TABLE `Order` MODIFY `paymentRef` TEXT NULL;
ALTER TABLE `Order` MODIFY `shippingMethod` TEXT NULL;
ALTER TABLE `Order` MODIFY `shippingZone` TEXT NULL;
ALTER TABLE `Order` MODIFY `shipArea` TEXT NULL;
ALTER TABLE `Order` MODIFY `shipStreet` TEXT NOT NULL;
ALTER TABLE `Order` MODIFY `customerNote` TEXT NULL;
ALTER TABLE `Order` MODIFY `adminNote` TEXT NULL;
ALTER TABLE `Order` MODIFY `trackingNumber` TEXT NULL;
ALTER TABLE `Order` MODIFY `courier` TEXT NULL;
ALTER TABLE `Order` MODIFY `ipAddress` TEXT NULL;
ALTER TABLE `Order` MODIFY `userAgent` TEXT NULL;
ALTER TABLE `OrderItem` MODIFY `productName` TEXT NOT NULL;
ALTER TABLE `OrderItem` MODIFY `sku` TEXT NULL;
ALTER TABLE `OrderItem` MODIFY `image` TEXT NULL;
ALTER TABLE `OrderEvent` MODIFY `note` TEXT NULL;
ALTER TABLE `OrderEvent` MODIFY `by` TEXT NULL;
ALTER TABLE `Coupon` MODIFY `description` TEXT NULL;
ALTER TABLE `Coupon` MODIFY `targetIds` TEXT NULL;
ALTER TABLE `Review` MODIFY `title` TEXT NULL;
ALTER TABLE `Review` MODIFY `body` TEXT NOT NULL;
ALTER TABLE `Page` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `Page` MODIFY `titleBn` TEXT NULL;
ALTER TABLE `Page` MODIFY `content` LONGTEXT NOT NULL;
ALTER TABLE `Page` MODIFY `excerpt` TEXT NULL;
ALTER TABLE `Page` MODIFY `featuredImage` TEXT NULL;
ALTER TABLE `Page` MODIFY `metaTitle` TEXT NULL;
ALTER TABLE `Page` MODIFY `metaDesc` TEXT NULL;
ALTER TABLE `Page` MODIFY `metaKeywords` TEXT NULL;
ALTER TABLE `Post` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `Post` MODIFY `excerpt` TEXT NULL;
ALTER TABLE `Post` MODIFY `content` LONGTEXT NOT NULL;
ALTER TABLE `Post` MODIFY `coverImage` TEXT NULL;
ALTER TABLE `Post` MODIFY `category` TEXT NULL;
ALTER TABLE `Post` MODIFY `tags` TEXT NULL;
ALTER TABLE `Post` MODIFY `authorName` TEXT NOT NULL DEFAULT 'BD Market Team';
ALTER TABLE `Post` MODIFY `metaTitle` TEXT NULL;
ALTER TABLE `Post` MODIFY `metaDesc` TEXT NULL;
ALTER TABLE `Menu` MODIFY `items` TEXT NOT NULL;
ALTER TABLE `Banner` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `Banner` MODIFY `subtitle` TEXT NULL;
ALTER TABLE `Banner` MODIFY `image` TEXT NOT NULL;
ALTER TABLE `Banner` MODIFY `ctaLabel` TEXT NULL;
ALTER TABLE `Banner` MODIFY `ctaHref` TEXT NULL;
ALTER TABLE `Banner` MODIFY `bgColor` TEXT NULL;
ALTER TABLE `Banner` MODIFY `textColor` TEXT NULL;
ALTER TABLE `Media` MODIFY `filename` TEXT NOT NULL;
ALTER TABLE `Media` MODIFY `url` TEXT NOT NULL;
ALTER TABLE `Media` MODIFY `mimeType` TEXT NULL;
ALTER TABLE `Media` MODIFY `alt` TEXT NULL;
ALTER TABLE `Setting` MODIFY `value` TEXT NOT NULL;
ALTER TABLE `ShippingZone` MODIFY `districts` TEXT NOT NULL;
ALTER TABLE `PaymentMethod` MODIFY `description` TEXT NULL;
ALTER TABLE `PaymentMethod` MODIFY `icon` TEXT NULL;
ALTER TABLE `PaymentMethod` MODIFY `instructions` TEXT NULL;
ALTER TABLE `PaymentMethod` MODIFY `config` TEXT NULL;
ALTER TABLE `PageView` MODIFY `path` TEXT NOT NULL;
ALTER TABLE `PageView` MODIFY `referrer` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `title` TEXT NOT NULL;
ALTER TABLE `LandingPage` MODIFY `blocks` LONGTEXT NOT NULL;
ALTER TABLE `LandingPage` MODIFY `metaTitle` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `metaDesc` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `metaKeywords` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `ogImage` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `canonical` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `gaId` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `fbPixelId` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `customHead` LONGTEXT NULL;
ALTER TABLE `LandingPage` MODIFY `customBody` LONGTEXT NULL;
ALTER TABLE `LandingPage` MODIFY `bgColor` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `textColor` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `fontFamily` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `checkoutHeading` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `checkoutFields` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `checkoutButton` TEXT NULL;
ALTER TABLE `LandingPage` MODIFY `thankYouNote` TEXT NULL;
