/**
 * Colour helpers shared by the admin theme picker and the storefront theme injector.
 *
 * The storefront receives a single accent colour from Settings → Appearance, so
 * everything else (hover shade, tint, border, readable text) is derived here.
 * Keeping this in one place means the swatch a merchant sees in the admin preview
 * is generated by exactly the same maths that runs on the storefront.
 */

export type RGB = { r: number; g: number; b: number };
export type HSL = { h: number; s: number; l: number };

/** Expand `#abc` → `#aabbcc` and normalise case. Returns null for anything else. */
export function normalizeHex(input: string): string | null {
  if (typeof input !== 'string') return null;
  let h = input.trim().toLowerCase();
  if (h.startsWith('#')) h = h.slice(1);
  if (/^[0-9a-f]{3}$/.test(h)) h = h.split('').map((c) => c + c).join('');
  if (!/^[0-9a-f]{6}$/.test(h)) return null;
  return `#${h}`;
}

export function isValidHex(input: string): boolean {
  return normalizeHex(input) !== null;
}

export function hexToRgb(hex: string): RGB {
  const h = normalizeHex(hex) ?? '#000000';
  return {
    r: parseInt(h.slice(1, 3), 16),
    g: parseInt(h.slice(3, 5), 16),
    b: parseInt(h.slice(5, 7), 16),
  };
}

export function rgbToHex({ r, g, b }: RGB): string {
  const c = (n: number) => Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, '0');
  return `#${c(r)}${c(g)}${c(b)}`;
}

export function hexToHsl(hex: string): HSL {
  const { r, g, b } = hexToRgb(hex);
  const rn = r / 255;
  const gn = g / 255;
  const bn = b / 255;
  const max = Math.max(rn, gn, bn);
  const min = Math.min(rn, gn, bn);
  const d = max - min;
  let h = 0;

  if (d !== 0) {
    if (max === rn) h = ((gn - bn) / d) % 6;
    else if (max === gn) h = (bn - rn) / d + 2;
    else h = (rn - gn) / d + 4;
    h *= 60;
    if (h < 0) h += 360;
  }

  const l = (max + min) / 2;
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1));
  return { h, s: s * 100, l: l * 100 };
}

export function hslToHex({ h, s, l }: HSL): string {
  const sn = Math.max(0, Math.min(100, s)) / 100;
  const ln = Math.max(0, Math.min(100, l)) / 100;
  const hh = ((h % 360) + 360) % 360;
  const c = (1 - Math.abs(2 * ln - 1)) * sn;
  const x = c * (1 - Math.abs(((hh / 60) % 2) - 1));
  const m = ln - c / 2;

  let rgb: [number, number, number];
  if (hh < 60) rgb = [c, x, 0];
  else if (hh < 120) rgb = [x, c, 0];
  else if (hh < 180) rgb = [0, c, x];
  else if (hh < 240) rgb = [0, x, c];
  else if (hh < 300) rgb = [x, 0, c];
  else rgb = [c, 0, x];

  return rgbToHex({ r: (rgb[0] + m) * 255, g: (rgb[1] + m) * 255, b: (rgb[2] + m) * 255 });
}

/** Shift lightness by `delta` percentage points, keeping hue and saturation. */
export function shiftLightness(hex: string, delta: number): string {
  const { h, s, l } = hexToHsl(hex);
  return hslToHex({ h, s, l: l + delta });
}

/** Relative luminance per WCAG 2.1. */
export function luminance(hex: string): number {
  const { r, g, b } = hexToRgb(hex);
  const channel = (v: number) => {
    const n = v / 255;
    return n <= 0.03928 ? n / 12.92 : Math.pow((n + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

export function contrastRatio(a: string, b: string): number {
  const la = luminance(a);
  const lb = luminance(b);
  const light = Math.max(la, lb);
  const dark = Math.min(la, lb);
  return (light + 0.05) / (dark + 0.05);
}

/** Black or white, whichever is more legible on `hex`. */
export function readableOn(hex: string): '#ffffff' | '#1f2533' {
  return contrastRatio(hex, '#ffffff') >= contrastRatio(hex, '#1f2533') ? '#ffffff' : '#1f2533';
}

/** Darken for hover states; lighten if the colour is already near-black. */
export function hoverShade(hex: string): string {
  const { l } = hexToHsl(hex);
  return l < 20 ? shiftLightness(hex, 12) : shiftLightness(hex, -8);
}

/**
 * Derive the full token set the storefront needs from one seed colour.
 *
 * The generator pins lightness (not the raw channel values) so that any hue a
 * merchant picks still yields a usable ramp. Only `h` and `s` come from the seed.
 *
 * The two dark "ink" stops are deliberately *not* derived from the seed. They
 * back body text, headings, the footer and every dark panel, and a hue-shifted
 * near-black reads as a colour cast — a merchant choosing orange would get
 * brown body text. They stay neutral charcoal regardless of the accent.
 */
export function buildRamp(hex: string) {
  const seed = normalizeHex(hex) ?? '#006a4e';
  const { h, s } = hexToHsl(seed);

  const at = (l: number) => hslToHex({ h, s, l });
  const L = {
    50: 96.5,
    100: 93,
    200: 85,
    300: 73,
    400: 58,
    500: 45,
    600: 34,
    700: 28,
    800: 23,
    900: 18,
    950: 11,
  };

  const ramp = Object.fromEntries(
    Object.entries(L).map(([stop, l]) => [stop, at(l)])
  ) as Record<keyof typeof L, string>;

  // The merchant's exact colour wins for the mid-tones they actually see.
  ramp[600] = seed;
  ramp[700] = hoverShade(seed);
  ramp[500] = shiftLightness(seed, 9);

  return {
    ...ramp,
    hover: ramp[700],
    on: readableOn(seed),
    soft: ramp[50],
    // Neutral, hue-free — see the note above.
    ink900: '#1f2533',
    ink950: '#12151f',
  };
}

/**
 * Curated presets. Each one ships the derived ramp so the admin swatches can
 * preview real storefront colours without running the generator in the browser.
 */
export const PRESETS: { name: string; hex: string; note: string; dark?: boolean }[] = [
  { name: 'Bangladesh Green', hex: '#006a4e', note: 'Default brand colour', dark: true },
  { name: 'Emerald', hex: '#047857', note: 'Fresh, retail-friendly' },
  { name: 'Teal', hex: '#0f766e', note: 'Calm and trustworthy' },
  { name: 'Royal Blue', hex: '#1d4ed8', note: 'Widely used in ecommerce' },
  { name: 'Indigo', hex: '#4338ca', note: 'Modern, premium feel' },
  { name: 'Deep Purple', hex: '#6d28d9', note: 'Bold and creative' },
  { name: 'Crimson', hex: '#be123c', note: 'High urgency, sale-driven' },
  { name: 'Orange', hex: '#c2410c', note: 'Warm and energetic' },
  { name: 'Amber', hex: '#b45309', note: 'Use with dark text' },
  { name: 'Slate', hex: '#334155', note: 'Neutral, editorial' },
  { name: 'Charcoal', hex: '#1f2533', note: 'Minimal monochrome' },
  { name: 'Hot Pink', hex: '#be185d', note: 'Fashion and beauty' },
];

/** Rough usability verdict shown under the preview. */
export function themeAdvice(hex: string): { level: 'ok' | 'warn'; message: string } {
  const { s, l } = hexToHsl(hex);

  if (l > 62) {
    return {
      level: 'warn',
      message: 'Very light — white text will be hard to read on buttons. Try a darker shade.',
    };
  }
  if (l < 12) {
    return {
      level: 'warn',
      message: 'Almost black — the active states will not be distinguishable. Try a slightly lighter shade.',
    };
  }
  if (s < 12) {
    return {
      level: 'warn',
      message: 'Nearly grey — links and buttons will look washed out. Add some saturation.',
    };
  }
  return {
    level: 'ok',
    message: `Good contrast — buttons will use ${readableOn(hex) === '#ffffff' ? 'white' : 'dark'} text.`,
  };
}
