/**
 * Which columns carry an explicit MySQL native type, and which one.
 *
 * Prisma maps a plain `String` to VARCHAR(191) on MySQL, which silently
 * truncates long values — including the JSON in `Menu.items`, `Setting.value`
 * and `Product.images`, where truncation makes the value unparseable and the UI
 * renders empty.
 *
 * The annotation is invalid on SQLite (`Native type Text is not supported for
 * sqlite connector`), so `scripts/use-db.js` strips these when switching to
 * SQLite and re-applies them for MySQL and Postgres. Without that, switching to
 * SQLite leaves a schema Prisma refuses to load.
 *
 * GENERATED by scripts/gen-column-types.js — do not edit by hand.
 * 100 column(s) across 21 model(s).
 */

module.exports = {
  "User": {
    "avatar": "@db.Text"
  },
  "AuditLog": {
    "meta": "@db.Text"
  },
  "Customer": {
    "tags": "@db.Text",
    "notes": "@db.Text",
    "avatar": "@db.Text"
  },
  "Category": {
    "description": "@db.Text",
    "image": "@db.Text",
    "metaTitle": "@db.Text",
    "metaDesc": "@db.Text"
  },
  "Brand": {
    "logo": "@db.Text",
    "description": "@db.Text"
  },
  "Product": {
    "barcode": "@db.Text",
    "description": "@db.Text",
    "shortDesc": "@db.Text",
    "dimensions": "@db.Text",
    "images": "@db.Text",
    "tags": "@db.Text",
    "attributes": "@db.Text",
    "variants": "@db.Text",
    "careInstructions": "@db.Text",
    "metaTitle": "@db.Text",
    "metaDesc": "@db.Text",
    "metaKeywords": "@db.Text",
    "ogImage": "@db.Text",
    "canonical": "@db.Text"
  },
  "Order": {
    "paymentRef": "@db.Text",
    "shippingMethod": "@db.Text",
    "shippingZone": "@db.Text",
    "shipArea": "@db.Text",
    "shipStreet": "@db.Text",
    "customerNote": "@db.Text",
    "adminNote": "@db.Text",
    "trackingNumber": "@db.Text",
    "courier": "@db.Text",
    "ipAddress": "@db.Text",
    "userAgent": "@db.Text"
  },
  "OrderItem": {
    "productName": "@db.Text",
    "sku": "@db.Text",
    "image": "@db.Text"
  },
  "OrderEvent": {
    "note": "@db.Text",
    "by": "@db.Text"
  },
  "Coupon": {
    "description": "@db.Text",
    "targetIds": "@db.Text"
  },
  "Review": {
    "title": "@db.Text",
    "body": "@db.Text"
  },
  "Page": {
    "title": "@db.Text",
    "titleBn": "@db.Text",
    "content": "@db.LongText",
    "excerpt": "@db.Text",
    "featuredImage": "@db.Text",
    "metaTitle": "@db.Text",
    "metaDesc": "@db.Text",
    "metaKeywords": "@db.Text"
  },
  "Post": {
    "title": "@db.Text",
    "excerpt": "@db.Text",
    "content": "@db.LongText",
    "coverImage": "@db.Text",
    "category": "@db.Text",
    "tags": "@db.Text",
    "authorName": "@db.Text",
    "metaTitle": "@db.Text",
    "metaDesc": "@db.Text"
  },
  "Menu": {
    "items": "@db.Text"
  },
  "Banner": {
    "title": "@db.Text",
    "subtitle": "@db.Text",
    "image": "@db.Text",
    "ctaLabel": "@db.Text",
    "ctaHref": "@db.Text",
    "bgColor": "@db.Text",
    "textColor": "@db.Text"
  },
  "Media": {
    "filename": "@db.Text",
    "url": "@db.Text",
    "mimeType": "@db.Text",
    "alt": "@db.Text"
  },
  "Setting": {
    "value": "@db.Text"
  },
  "ShippingZone": {
    "districts": "@db.Text"
  },
  "PaymentMethod": {
    "description": "@db.Text",
    "icon": "@db.Text",
    "instructions": "@db.Text",
    "config": "@db.Text"
  },
  "PageView": {
    "path": "@db.Text",
    "referrer": "@db.Text"
  },
  "LandingPage": {
    "title": "@db.Text",
    "blocks": "@db.LongText",
    "metaTitle": "@db.Text",
    "metaDesc": "@db.Text",
    "metaKeywords": "@db.Text",
    "ogImage": "@db.Text",
    "canonical": "@db.Text",
    "gaId": "@db.Text",
    "fbPixelId": "@db.Text",
    "customHead": "@db.LongText",
    "customBody": "@db.LongText",
    "bgColor": "@db.Text",
    "textColor": "@db.Text",
    "fontFamily": "@db.Text",
    "checkoutHeading": "@db.Text",
    "checkoutFields": "@db.Text",
    "checkoutButton": "@db.Text",
    "thankYouNote": "@db.Text"
  }
};
